name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  packages: read
jobs:
  lint:
    strategy:
      matrix:
        language: [ js, ts ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./${{ matrix.language }}/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-
      - name: Install
        run: npm install
        working-directory: ./${{ matrix.language }}
      - name: Lint check
        run: npm run fmt-check
        working-directory: ./${{ matrix.language }}
  build-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./ts/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-
      - name: Install
        run: npm install
        working-directory: ./ts
      - name: Build Typescript Files
        run: npm run build
        working-directory: ./ts
      - name: Verify migrations generated
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "you need to run 'npm run build' and commit the changes"
            echo "$status"
            git --no-pager diff
            exit 1
           fi
  integration-tests:
    strategy:
      matrix:
        dialect: [ mysql, postgres, sqlite, mssql ]
        language: [ js, ts ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./${{ matrix.language }}/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-
      - name: Install
        run: npm install
        working-directory: ./${{ matrix.language }}
      - uses: ariga/setup-atlas@master
      - name: Run Test as Standalone
        working-directory: ./${{ matrix.language }}/testdata
        run: |
          atlas migrate diff --env sequelize -c "file://atlas-standalone.hcl" --var dialect=${{ matrix.dialect }}
      - name: Verify migrations generated
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "you need to run 'atlas migrate diff --env sequelize' and commit the changes"
            echo "$status"
            git --no-pager diff
            exit 1
           fi
      - name: Run Test as ${{ matrix.language }} Script
        working-directory: ./${{ matrix.language }}/testdata
        run: |
          atlas migrate diff --env sequelize -c "file://atlas-script.hcl" --var dialect=${{ matrix.dialect }}
      - name: Verify migrations generated
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "you need to run 'atlas migrate diff --env sequelize' and commit the changes"
            echo "$status"
            git --no-pager diff
            exit 1
           fi
