name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  packages: read
jobs:
  lintJS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./js/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-
      - name: Install
        run: npm install
        working-directory: ./js
      - name: Lint check
        run: npm run fmt
        working-directory: ./js
  lintTS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./ts/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-
      - name: Install
        run: npm install
        working-directory: ./ts
      - name: Lint check
        run: npm run fmt
        working-directory: ./ts